# Copyright (c) 2018, NVIDIA CORPORATION.

dist: trusty
sudo: required
language: cpp

git:
  depth: false

branches:
    only:
        - master
env:
  global:
     secure: "EHU4ahNqfqSaT+VQ3cc3MRpHgfIg/K+NUXszlsVzbFgDR43LJD61QavtPMzNM73eVZRzvgRD39yYgHjDF6ZhQ4OpSEGzBiNEzAjKLqnl1JWd7V7/L31OiDsJMwweksrWINoKLPzikr2mOecsWGmRJYcLfYeJZcGlf67PuCN6DI2Un/pYXzblKfU2dVg8bP+HdWrnXTT6u4abnjCU+4kwc+kl9NJzLI1Zk5pSDuLkgRbiF90lImofYh8GfjyUhiz1Hnq+TjKOToLNOLxXMuM6NFxAIsdFfNkklXaz/mhQom3ZYfMlkjwWz/vJ0BKk554bq4mfL71yBzgydvprSppI0qfHtEvVIR2OJy9HnPvOiHdh7aL1qOojC00zjj39PyIx8M61ovpOvJOVD0c2/vBr6Et5JGastULJq2ItzHyP6UNn4oZtinmXV061sNSOepVjEstHMLVytP87cmiMMiBeDncFV/Sl3y5w1l7rGFVn4lNr2XDMl0u+WnDbZ9n57qneAweeoYkS0tBDdcVzfhv6+RJd129NNtgJtk4fWkh387kOeAOPz+uqu6GNFgXRT/zmRI8sttMkyjSBQeKLTGkCDrboqlU1DZ2lyORiQ3P2yOdNeBTkDJFvdntYduHM7tzhTFUOoVaOn0aFK+zE+AwLkw1JJEvi4g1tVI+iKuDZd/Y="

matrix:
  include:
#    - env: CUDA=9.0.176_384.81
#    - env: CUDA=9.1.85_387.26
#    - env: CUDA=9.2.148_396.37
    - env: CUDA=9.0.176_384.81 BUILD_CFFI=1 PYTHON=3.6
#    - env: CUDA=9.0.176_384.81 BUILD_CFFI=1 PYTHON=3.5

#addons:
#  apt:
#    sources:
#      - ubuntu-toolchain-r-test
#    packages:
#      - g++-5
#    update:
#      - true

before_install:
  # update links for gcc-5
  # install gcc-5
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install -y g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 1 --slave /usr/bin/gcc gcc /usr/bin/gcc-5
  - eval "${CC} --version"
  - eval "${CXX} --version"

  # Install CUDA toolkit
  - source ./travisci/install-cuda-trusty.sh

  # install miniconda
  - travis_retry wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda3/bin:$PATH

  # install libboost
  - sudo apt-get install -y libboost-all-dev

install:
  # check
  - nvcc --version
  - conda --version
  # install conda build
  - conda install conda-build anaconda-client conda-verify --yes

script:
  # build ligdf
  - source ./travisci/build_libgdf.sh
  # build libgdf_cffi
  - source ./travisci/build_libgdf_cffi.sh

after_success:
  - source ./travisci/upload.sh
