
set(CUDA_LIBRARY_DIR       ${CUDA_TOOLKIT_ROOT_DIR})
set(CUDA_LIBRARY_STUBS_DIR ${CUDA_TOOLKIT_ROOT_DIR})

## Based on NVRTC (Runtime Compilation) - CUDA Toolkit Documentation - v9.2.148
## 2.2. Installation
if(CMAKE_HOST_APPLE)
    set(CUDA_LIBRARY_DIR       ${CUDA_TOOLKIT_ROOT_DIR}/lib)
    set(CUDA_LIBRARY_STUBS_DIR ${CUDA_TOOLKIT_ROOT_DIR}/lib/stubs)
elseif(CMAKE_HOST_UNIX)
    set(CUDA_LIBRARY_DIR       ${CUDA_TOOLKIT_ROOT_DIR}/lib64)
    set(CUDA_LIBRARY_STUBS_DIR ${CUDA_TOOLKIT_ROOT_DIR}/lib64/stubs)
elseif(CMAKE_HOST_WIN32)
    set(CUDA_LIBRARY_DIR       ${CUDA_TOOLKIT_ROOT_DIR}\lib\x64)
    set(CUDA_LIBRARY_STUBS_DIR ${CUDA_TOOLKIT_ROOT_DIR}\lib\x64\stubs)
endif()

set(CUDA_CUDA_LIB  cuda)
set(CUDA_NVRTC_LIB nvrtc)

message("-- CUDA_LIBRARY_DIR: ${CUDA_LIBRARY_DIR}")
message("-- CUDA_LIBRARY_STUBS_DIR: ${CUDA_LIBRARY_STUBS_DIR}")
